FROM rust:1.93

WORKDIR /workspaces/rws/crates/websvc
COPY . .

ENV OUTPUT_PATH_PREFIX="/data/output/"
ENV SOURCE_PATH="crates/estractor/data/sources-.csv"
ENV ISIN_PATH_PREFIX "crates/estractor/data/"
ENV LISTEN_PORT 8080
EXPOSE 8080

RUN cargo install --path ./crates/websvc

CMD ["websvc"]