[package]
name = "tests"
version = "0.1.0"
edition = "2024"
authors = ["Michelangelo <ms.co.it@gmail.com>"]

# [lib]
# crate-type = ["cdylib"]

[dependencies]
glob = "0.3.3"
regex = "1.12.3"
# worker = { version = "0.7", features = ['d1'] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
